joint1:
  limit:
    lower:      -2.7437
    upper:       2.7437
    velocity:    2.62
    effort:     87.0

joint2:
  limit:
    lower:     -1.7837
    upper:      1.7837
    velocity:   2.62
    effort:    87.0

joint3:
  limit:
    lower:     -2.9007
    upper:      2.9007
    velocity:   2.62
    effort:    87.0

joint4:
  limit:
    lower:     -3.0421
    upper:     -0.1518
    velocity:   2.62
    effort:    87.0

joint5:
  limit:
    lower:     -2.8065
    upper:      2.8065
    velocity:   5.26
    effort:    12.0

joint6:
  limit:
    lower:      0.5445
    upper:      4.5169
    velocity:   4.18
    effort:    12.0

joint7:
  limit:
    lower:     -3.0159
    upper:      3.0159
    velocity:   5.26
    effort:    12.0

joint_limits:
  fr3_joint1:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_joint2:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 7.5
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_joint3:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_joint4:
    has_velocity_limits: true
    max_velocity: 2.1750
    has_acceleration_limits: true
    max_acceleration: 12.5
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_joint5:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 15.0
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_joint6:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_joint7:
    has_velocity_limits: true
    max_velocity: 2.6100
    has_acceleration_limits: true
    max_acceleration: 20.0
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 300.0
  fr3_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 300.0
